name: Keep Replit Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分鐘觸發一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  ping:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 操作系統

    steps:
    - name: Ping Replit app
      run: |
        curl -X GET https://line-message-hub-kc006574.replit.app/  # 請替換為你的 Replit 應用 URL
